apiVersion: v1
kind: Service
metadata:
  name: bes-oss-data-analyst-vercel
  namespace: aidc-dev
spec:
  type: NodePort
  ports:
  - port: 60055 # must change
    targetPort: 3000 # must be same as deployment containerPort
    nodePort: 31362 # must change
    protocol: TCP
    name: http
  selector:
    app: bes-oss-data-analyst-vercel